#!/usr/bin/env zsh

. ~/.scripts/defs

# Snapshot erstellen
# sudo timeshift --btrfs --create

# System Update
if [ $IS_ARCH_BASED = true ]; then
	$PACTOOL -Syyu --needed
fi

if [ $IS_RH_BASED = true ]; then
	sudo $PACTOOL update -y
fi

# Flatpak Update
flatpak update -v --noninteractive

# Zinit Self update
. "$HOME/.zinit/bin/zinit.zsh"
zinit self-update

# Zinit Plugin update
zinit update --parallel
