#!/usr/bin/env zsh

. ~/.scripts/defs

# Init Install
initInstall "install_base"

###########################
# collect needed packages #
###########################

# Manjaro Packages
if [ $IS_MANJARO = true ]; then
    install samba
    install manjaro-settings-samba
fi

# ArcoLinux Packages
if [ $IS_ARCO = true ]; then
    # Meta Packages
    install arcolinux-meta-samba
fi

# system packages
if [ $IS_ARCH_BASED = true ]; then
    install ttf-devicons
    install fd
    install awesome-terminal-fonts
    install terminus-font
    install ttf-meslo-nerd-font-powerlevel10k
    install zsh-theme-powerlevel10k
	install bpytop
	install docker-compose
	install exa
	install lsd
	install fastfetch
	install openconnect
	install p7zip
	install unrar
	install multitail

	# language files
	install man-pages-de

	#####################
	# collect rust apps #
	#####################
	install bat
	install procs
	install ripgrep
	install tokei
	install git-delta

	# powerline in linux console
	install powerline-fonts

	# cockpit
	install cockpit-file-sharing
fi

# cockpit
install cockpit
install cockpit-packagekit
install cockpit-podman
install cockpit-sosreport
install cockpit-pcp
install cockpit-system

if [ $IS_FEDORA_BASED = true ]; then
    install dotnet-runtime-6.0
    install dotnet-runtime-7.0
fi

install docker
install iotop
install openssh
install time

if [ $IS_FEDORA_BASED = true ]; then
	# ranger + micro + plugins
    curl https://getmic.ro | bash
    sudo mv micro /usr/bin/
	errorCheck "micro install"

	git clone https://github.com/LinusDierheimer/fastfetch.git ~/fastfetch
	cd ~/fastfetch
    mkdir -p build
    cd build
    cmake ..
    cmake --build . --target fastfetch --target flashfetch
	errorCheck "fastfetch maker"
    sudo mv fastfetch /usr/bin
	errorCheck "fastfetch install"
    cd ../..
    sudo rm -fr ~/fastfetch    
fi

if [ $IS_ARCH_BASED = true ]; then
	# file manager
	install ranger

	# installation of important editors
	install micro
fi


###############################
# uninstall unneeded packages #
###############################
fullUninstall

#################################
# install all (needed) packages #
#################################
fullInstall

## FINISHING #
finish

# ranger plugins
if [ $IS_CENTOS = true -o $IS_RHEL = true ]; then
    git clone https://github.com/hut/ranger.git
    cd ranger
    sudo make install
    ranger --copy-config=all
fi

if [ $IS_ARCH_BASED = true ]; then
    mkdir "$HOME/.config/ranger/plugins"
    ln -sf /usr/share/ranger/plugins/ranger_devicons ~/.config/ranger/plugins/ranger_devicons
fi

micro -plugin install comment bounce editorconfig joinLines quoter filemanager bookmark \
jump detectindent go snippets crystal quickfix wc manipulator \
monokai-dark gotham-colors nordcolors
