#!/usr/bin/env zsh

. ~/.scripts/defs

# Init Install
initInstall "install_vm"

#####################
# init distro check #
#####################

INSTALL_VIRTIO=true
INSTALL_VIRTUALBOX=false

###########################
# collect needed packages #
###########################

# virtualbox
if [ $INSTALL_VIRTUALBOX = true ]; then
	if [ $IS_MANJARO = true ]; then
		install virtualbox
		install virtualbox-ext-oracle
	else
		install virtualbox
		install virtualbox-ext-oracle
		install virtualbox-host-modules-arch
		install linux-headers
	fi
fi

# libvirt service and manager
if [ $INSTALL_VIRTIO = true ]; then
	if [ $IS_FEDORA = false ]; then
		install virtio-win
		install qemu-desktop
		install qemu-arch-extra
		install vde2 
		install openbsd-netcat 
		install ovmf
	else
	fi
	
	install virt-manager
	install libvirt
	install iptables-nft
	install ebtables
	install dnsmasq
	install bridge-utils 
fi

###############################
# uninstall unneeded packages #
###############################
fullUninstall

#################################
# install all (needed) packages #
#################################
fullInstall

## FINISHING #
finish

sudo systemctl enable --now libvirtd
errorCheck "libvirtd service"
