#!/usr/bin/env zsh

. ~/.scripts/defs

# Init Install
initInstall "install_init"

# Config pacman
if [ -f /etc/pacman.conf ]; then
	sed 's/^#Color$/Color/g' </etc/pacman.conf >pacman.conf
	sudo mv pacman.conf /etc/
	sed 's/^.*ParallelDownloads.*$/ParallelDownloads = 5/g' </etc/pacman.conf >pacman.conf
	sudo mv pacman.conf /etc/
	sed 's/^.*VerbosePkgLists.*$/VerbosePkgLists/g' </etc/pacman.conf >pacman.conf
	sudo mv pacman.conf /etc/
	errorCheck "pacman config"
fi

# Config pamac
if [ -f /etc/pamac.conf ]; then
	sed 's/^.*ILoveCandy$/ILoveCandy/g' </etc/pamac.conf >pamac.conf
	sudo mv pamac.conf /etc/
	sed 's/^.*EnableAUR$/EnableAUR/g' </etc/pamac.conf >pamac.conf
	sudo mv pamac.conf /etc/
	sed 's/^.*KeepBuiltPkgs$/KeepBuiltPkgs/g' </etc/pamac.conf >pamac.conf
	sudo mv pamac.conf /etc/
	errorCheck "pamac config"
fi

if [ $IS_FEDORA_BASED = true ]; then
	sudo sudo $PACKER install git go ruby rust make
else
	sudo sudo $PACKER -S --needed git base-devel colorgcc go ruby rust
fi
errorCheck "installation base-devel"


# Prompt installieren
if [ $IS_FEDORA_BASED = false ]; then
	install ttf-meslo-nerd-font-powerlevel10k
	install zsh-theme-powerlevel10k
fi
errorCheck "installation prompt"

# disable sudo password
echo "Cmnd_Alias INSTALL = /usr/bin/pacman, /usr/share/pacman
Cmnd_Alias POWER = /usr/bin/pm-hibernate, /usr/bin/pm-powersave, /usr/bin/pm-suspend-hybrid, /usr/bin/pm-suspend
Defaults timestamp_timeout=300
$USER ALL=(ALL) NOPASSWD:INSTALL,POWER
$USER ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/100-myrules

chmod -R -v +x ~/.scripts
chmod -R -v +x ~/.bin
errorCheck "set script flags"

## FINISHING #
finish
