#!/usr/bin/env zsh

. ~/.scripts/defs

# Init Install
initInstall "install_vm"

#####################
# init distro check #
#####################

INSTALL_VIRTIO=true
INSTALL_VIRTUALBOX=false

###########################
# collect needed packages #
###########################

# virtualbox
if [ $INSTALL_VIRTUALBOX = true ]; then
	if [ $IS_MANJARO = true ]; then
		install virtualbox
		install virtualbox-ext-oracle
	else
		install virtualbox
		install virtualbox-ext-oracle
		install virtualbox-host-modules-arch
		install linux-headers
	fi
fi

# libvirt service and manager
if [ $INSTALL_VIRTIO = true ]; then
	if [ $IS_FEDORA_BASED = false ]; then
		install qemu-arch-extra
		install vde2 
		install openbsd-netcat 
		install ovmf
		install bridge-utils 
	fi
	
	install virtio-win
	install virt-manager
	install libvirt
	install iptables-nft
	install ebtables
	install dnsmasq
	install cockpit-machines	
fi

###############################
# uninstall unneeded packages #
###############################
fullUninstall

#################################
# install all (needed) packages #
#################################
fullInstall

## FINISHING #
finish

sudo systemctl enable --now libvirtd
errorCheck "libvirtd service"
