#!/usr/bin/env zsh

. ~/.scripts/defs

# Init Install
initInstall "install_base"

###########################
# collect needed packages #
###########################

# Manjaro Packages
if [ $IS_MANJARO = true ]; then
    install samba
    install manjaro-settings-samba
fi

# ArcoLinux Packages
if [ $IS_ARCO = true ]; then
    # Meta Packages
    install arcolinux-meta-samba
fi

# system packages
if [ $IS_FEDORA = false ]; then
	install archey4
	install alsi
	install bashtop
	install pfetch
	install lhasa
	install update-grub
	install ttf-devicons
	install fd
	install awesome-terminal-fonts
	install terminus-font
	install ttf-meslo-nerd-font-powerlevel10k
	install zsh-theme-powerlevel10k
else
	install vim-devicons
	install mono-complete
	install dotnet-runtime-6.0
	install dotnet-runtime-7.0
fi

install arj
install bpytop
install cpufetch
install docker
install docker-compose
install exa
install lsd
install iftop
install iotop
install iptraf-ng
install libsecret
install multitail
install neofetch
install fastfetch
install openconnect
install openssh
install p7zip
install time
install unrar
install tar

# language files
install man-pages-de

# file manager
install ranger

# installation of important editors
install micro

#####################
# collect rust apps #
#####################
install bat
install procs
install ripgrep
install tokei
install git-delta

# powerline in linux console
install powerline-fonts

###############################
# uninstall unneeded packages #
###############################
fullUninstall

#################################
# install all (needed) packages #
#################################
fullInstall

## FINISHING #
finish

# ranger plugins
if [ $IS_FEDORA = false ]; then
	mkdir "$HOME/.config/ranger/plugins"
	ln -sf /usr/share/ranger/plugins/ranger_devicons ~/.config/ranger/plugins/ranger_devicons
fi

# micro plugins
micro -plugin install comment bounce editorconfig joinLines quoter filemanager bookmark \
jump detectindent go snippets crystal quickfix wc manipulator \
monokai-dark gotham-colors nordcolors
