#!/usr/bin/env zsh

. ~/.scripts/defs

# Init Install
initInstall "install_dev"

###########################################
# collect for development needed packages #
###########################################

# Base Development Tools
if [ $IS_FEDORA = false ]; then
	install base-devel
	install gitflow-avh
	install gradle
	install jdk-openjdk
	install jdk8-openjdk
	install nodejs-emojione
	install nodejs-lts-gallium
	install nvm
	install yarn
	# DotNet/Mono Setup
	install dotnet-sdk
	install mono
	install mono-msbuild
else
	install yarnpkg
	# DotNet/Mono Setup
	install dotnet-sdk-6.0
	install dotnet-sdk-7.0
	install mono-complete
fi

install git
install git-delta
install pass
install nuget
install npm
install svn
install tk
install nsis
install jq
install python-pip

# utils for editors
install bash-completion
install clang
install gdb
install graphviz
install ripgrep
install shellcheck
install tar

###############################
# uninstall unneeded packages #
###############################
fullUninstall

#################################
# install all (needed) packages #
#################################
fullInstall

## FINISHING #
finish
