#!/usr/bin/env zsh

. ~/.scripts/defs

# Init Install
initInstall "install_dev"

###########################################
# collect for development needed packages #
###########################################

# Manjaro Packages
if [ $IS_MANJARO = true ]; then
fi

# Base Development Tools
install base-devel
install git
install gitflow-avh
install git-delta
install pass
install gradle
install jdk-openjdk
install jdk8-openjdk
install nodejs-emojione
install nodejs-lts-gallium
install nvm
install nuget
install npm
install svn
install yarn
install tk
install nsis
install jq
install python-pip

# DotNet/Mono Setup
install dotnet-sdk
install mono
install mono-msbuild

# utils for editors
install bash-completion
install clang
install fd
install gdb
install graphviz
install prettier
install ripgrep
install shellcheck
install tar

###############################
# uninstall unneeded packages #
###############################
fullUninstall

#################################
# install all (needed) packages #
#################################
fullInstall

## FINISHING #
finish
