#!/usr/bin/env zsh

. ~/.scripts/defs

# Init Install
initInstall "install_dev"

###########################################
# collect for development needed packages #
###########################################

# Base Development Tools
if [ $IS_ARCH_BASED = true ]; then
	install base-devel
	install gitflow-avh
	install gradle
	install jdk-openjdk
	install jdk8-openjdk
	install nodejs-emojione
	install nodejs-lts-gallium
	install nvm
	install yarn
	# DotNet/Mono Setup
	install dotnet-sdk
	install mono
	install mono-msbuild
	install git-delta
	install pass
	install nuget
	install nsis
	install ripgrep
	install shellcheck
fi

if [ $IS_FEDORA_BASED = true ]; then
	# DotNet/Mono Setup
	install dotnet-sdk-6.0
	install dotnet-sdk-7.0
fi

install cmake	
install cargo
install rust
install git
install npm
install svn
install tk
install jq
install python-pip

# utils for editors
install bash-completion
install clang
install gdb

###############################
# uninstall unneeded packages #
###############################
fullUninstall

#################################
# install all (needed) packages #
#################################
fullInstall

## FINISHING #
finish
